### ISSUE TITLE
App icon is missing

### ISSUE THREAD

**Issue by directhex** [flathub/org.virt_manager.virt-viewer#2]
![image](https://github.com/flathub/org.virt_manager.virt-viewer/assets/308992/2208d388-d653-4831-a31f-b61f9c1ea86e)

![image](https://github.com/flathub/org.virt_manager.virt-viewer/assets/308992/e11eafd1-bd9a-4ceb-9f91-e697dfaa89e3)

**Comment by berrange** [comment]
Oh, probably because our icon is called 'virt-viewer.png' rather than 'org.virt_manager.virt-viewer.png'

**Comment by kowalski7cc** [comment]
Can confirm the issue, i'll look into it after work.
Thanks! :+1:
